### ISSUE TITLE
link2 looks like it has the wrong type

### ISSUE THREAD

**Issue by rjmac** [maoe/lifted-async#16]
It is `MonadBase IO m => Async a -> Async a -> m ()`; it should probably be `MonadBase IO m => Async a -> Async b -> m ()` to mirror the signature of 'link2' in Async.

**Comment by maoe** [comment]
That's right. I'll fix it on Monday as I don't have access to my computer in the weekend.

**Comment by maoe** [comment]
Fixed in v0.7.0.
