### ISSUE TITLE
Make a revision on hackage to support GHC 9.0

### ISSUE THREAD

**Issue by andreasabel** [maoe/lifted-async#32]
GHC 9.0 was released.  `lifted-async` does not build because of the constraint on `base`.
I successfully tried:
```
cabal install --allow-newer lifted-async
```
I suggest to make a revision on hackage (https://hackage.haskell.org/package/lifted-async/maintain) that lifts the necessary upper bounds to allow compilation with GHC 9.0.

UPDATE: 
- [x] Blocked by https://github.com/tibbe/hashable/issues/193.

**Comment by maoe** [comment]
Thanks for reporting.

I'm waiting for a dependency to be updated. The constraints package cannot build with 9.0.1 because the hashable package needs to be revised.

**Comment by andreasabel** [comment]
I successfully tested building `lifted-async-0.10.1.2` just now with a relaxed upper bound on `base` (see below [1]).

So a new release does not seem necessary, just a _revision_ of metadata on hackage.
https://github.com/haskell-infra/hackage-trustees/blob/master/cookbook.md#best-practice-for-managing-meta-data

E.g. here is my workflow for revisions: https://github.com/haskell-pkg-janitors/haskell-src/blob/540fc48dc2f0f2c75699315df950ff26e1918270/CONTRIBUTING.md

But it seems you are also planning to fix some warnings in #33, so this is of course not suitable for a revision...

[1] build test:
```
lifted-async-0.10.1.2$ cabal test
Resolving dependencies...
Build profile: -w ghc-9.0.1 -O1
In order, the following will be built (use -v for more details):
 - haskell-src-exts-1.23.1 (lib) (requires build)
 - semigroups-0.19.1 (lib) (requires build)
 - tasty-1.4.1 (lib) (requires build)
 - constraints-0.12 (lib) (requires build)
 - tasty-expected-failure-0.12.3 (lib) (requires download & build)
 - tasty-th-0.1.7 (lib) (requires download & build)
 - tasty-hunit-0.10.0.3 (lib) (requires build)
 - lifted-async-0.10.1.2 (lib) (first run)
 - lifted-async-0.10.1.2 (test:test-lifted-async) (first run)
 - lifted-async-0.10.1.2 (test:regression-tests) (first run)
...
Test suite test-lifted-async: RUNNING...
Test suite test-lifted-async: PASS
...
Test suite regression-tests: RUNNING...
Test suite regression-tests: PASS
```

**Comment by maoe** [comment]
Sorry for the delay. Just uploaded https://hackage.haskell.org/package/lifted-async-0.10.1.3.

**Comment by andreasabel** [comment]
Excellent, thank you!  Works for me.
