### ISSUE TITLE
withAsync can leak threads in MaybeT/ExceptT monads

### ISSUE THREAD

**Issue by Shimuuar** [maoe/lifted-async#34]
Reproducer:

```haskell
module Q where

import Control.Concurrent
import Control.Monad
import Control.Monad.Trans.Maybe
import Control.Monad.IO.Class
import Control.Concurrent.Async.Lifted

dumb :: IO ()
dumb = forever $ do threadDelay 100000
                    putStrLn "still alive"
  
go :: MaybeT IO ()
go = withAsync (liftIO dumb) $ \_ ->
  liftIO (threadDelay 10000) >> mzero
```

instead of killing async after `go` is finished thread is left running. Reason for that is simple: `withAsyncUsing` uses monadic bind from `m` which could abort early without ever reaching [stop](https://github.com/maoe/lifted-async/blob/9e42a944e4b8ff86adf41b7aa209c14e6ba27ed2/src/Control/Concurrent/Async/Lifted.hs#L196)

**Comment by maoe** [comment]
Thanks for reporting the issue with the nice repro.

I guess we need to change withAsyncUsing like this:

```diff
 withAsyncUsing fork action inner = E.mask $ \restore -> do
   a <- fork $ restore action
-  r <- restore (inner a) `E.catch` \e -> do
-    cancel a
-    E.throwIO (e :: SomeException)
-  cancel a
-  return r
+  restore (inner a)
+    `E.finally` cancel a
+    `E.catch` \e -> do
+      cancel a
+      E.throwIO (e :: SomeException)
```

I'm going to test this hopefully in the weekend. It seems that this function in the async package has changed quite a bit since last time I checked so I need to check that too.

**Comment by maoe** [comment]
The catch is no longer needed with the change, I guess. I'll check this too.

**Comment by Shimuuar** [comment]
Another option would be to drop into IO and use `withAsync` from async. It's not very [simple](https://hackage.haskell.org/package/async-2.2.3/docs/src/Control.Concurrent.Async.html#withAsyncUsing) and I think for good reason

**Comment by maoe** [comment]
Sorry I was a bit busy these days. I pushed a fix in #35.

Do you have a fix with your suggestion? If so could you make a PR so we can compare it with #35?

**Comment by Shimuuar** [comment]
No worries I'm not in hurry. Actually I found bug doing code review when considering lifted-async as dependency and in the end decided against it. Async turned out to be wrong abstaction. Then I reported bug anyway

**Comment by maoe** [comment]
Released as https://hackage.haskell.org/package/lifted-async-0.10.2. Thanks!
